name: RainGauge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - matplotlib
  - requests
  - geopy
  - pydeck
  - pip
  - pip:
      - streamlit-js-eval
      - meteostat